name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r event_hub/requirements.txt

      - name: Lint
        run: |
          cd event_hub
          make lint

      - name: Run tests
        run: |
          cd event_hub
          make test-coverage

      - name: Build Docker image
        run: |
          cd event_hub
          docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ secrets.DOCKER_REPO }}:latest
          docker push ${{ secrets.DOCKER_REPO }}:latest

      - name: Helm lint
        run: |
          helm lint event_hub/chart 